-- Super Shine shared database for the customer app and owner dashboard.
-- Run this complete file once in Supabase > SQL Editor.

create extension if not exists pgcrypto;

create sequence if not exists public.order_number_seq start with 1053;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text not null default '',
  phone text not null default '',
  role text not null default 'customer' check (role in ('customer', 'admin', 'driver')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  label text not null,
  address_line text not null,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id text primary key,
  name text not null,
  description text not null default '',
  price numeric(10, 2) not null check (price >= 0),
  price_unit text not null,
  enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coupons (
  code text primary key,
  title text not null,
  discount_type text not null check (discount_type in ('percentage', 'fixed', 'free_pickup')),
  discount_value numeric(10, 2) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default ('SS-' || lpad(nextval('public.order_number_seq')::text, 4, '0')),
  user_id uuid not null references public.profiles(id) on delete restrict,
  service_id text references public.services(id) on delete set null,
  service_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  item_summary text not null,
  subtotal numeric(10, 2) not null default 0 check (subtotal >= 0),
  express_fee numeric(10, 2) not null default 0 check (express_fee >= 0),
  discount numeric(10, 2) not null default 0 check (discount >= 0),
  total numeric(10, 2) not null default 0 check (total >= 0),
  pickup_slot text not null,
  pickup_address text not null,
  payment_method text not null check (payment_method in ('cash', 'promptpay', 'card')),
  express boolean not null default false,
  priority boolean not null default false,
  status text not null default 'New' check (status in ('New', 'Accepted', 'Pickup', 'Washing', 'Ready', 'Delivered', 'Cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null,
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  order_id uuid references public.orders(id) on delete cascade,
  title text not null,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists orders_user_id_created_at_idx on public.orders(user_id, created_at desc);
create index if not exists orders_status_created_at_idx on public.orders(status, created_at desc);
create index if not exists notifications_user_id_created_at_idx on public.notifications(user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'phone', '')
  )
  on conflict (id) do update set
    full_name = excluded.full_name,
    email = excluded.email,
    updated_at = now();
  return new;
end;
$$;

create or replace function public.protect_profile_role()
returns trigger
language plpgsql
as $$
begin
  if auth.uid() is not null and old.role is distinct from new.role and not public.is_admin() then
    raise exception 'Only an admin can change account roles';
  end if;
  return new;
end;
$$;

create or replace function public.record_order_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or old.status is distinct from new.status then
    insert into public.order_status_history (order_id, status, note)
    values (new.id, new.status, case when tg_op = 'INSERT' then 'Order placed' else 'Status updated' end);

    insert into public.notifications (user_id, order_id, title, body)
    values (
      new.user_id,
      new.id,
      case when tg_op = 'INSERT' then 'Order confirmed' else 'Order status updated' end,
      case
        when tg_op = 'INSERT' then 'Your order ' || new.order_number || ' has been received.'
        else 'Order ' || new.order_number || ' is now ' || lower(new.status) || '.'
      end
    );
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function public.handle_new_user();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists profiles_protect_role on public.profiles;
create trigger profiles_protect_role before update of role on public.profiles
for each row execute function public.protect_profile_role();

drop trigger if exists addresses_set_updated_at on public.addresses;
create trigger addresses_set_updated_at before update on public.addresses
for each row execute function public.set_updated_at();

drop trigger if exists services_set_updated_at on public.services;
create trigger services_set_updated_at before update on public.services
for each row execute function public.set_updated_at();

drop trigger if exists coupons_set_updated_at on public.coupons;
create trigger coupons_set_updated_at before update on public.coupons
for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists orders_record_status on public.orders;
create trigger orders_record_status after insert or update of status on public.orders
for each row execute function public.record_order_status();

alter table public.profiles enable row level security;
alter table public.addresses enable row level security;
alter table public.services enable row level security;
alter table public.coupons enable row level security;
alter table public.orders enable row level security;
alter table public.order_status_history enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "profiles_read_own_or_admin" on public.profiles;
create policy "profiles_read_own_or_admin" on public.profiles for select
using (id = auth.uid() or public.is_admin());
drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin" on public.profiles for update
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

drop policy if exists "addresses_read_own_or_admin" on public.addresses;
create policy "addresses_read_own_or_admin" on public.addresses for select
using (user_id = auth.uid() or public.is_admin());
drop policy if exists "addresses_insert_own_or_admin" on public.addresses;
create policy "addresses_insert_own_or_admin" on public.addresses for insert
with check (user_id = auth.uid() or public.is_admin());
drop policy if exists "addresses_update_own_or_admin" on public.addresses;
create policy "addresses_update_own_or_admin" on public.addresses for update
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());
drop policy if exists "addresses_delete_own_or_admin" on public.addresses;
create policy "addresses_delete_own_or_admin" on public.addresses for delete
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "services_read_authenticated" on public.services;
create policy "services_read_authenticated" on public.services for select
using (auth.uid() is not null);
drop policy if exists "services_admin_write" on public.services;
create policy "services_admin_write" on public.services for all
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "coupons_read_authenticated" on public.coupons;
create policy "coupons_read_authenticated" on public.coupons for select
using (auth.uid() is not null);
drop policy if exists "coupons_admin_write" on public.coupons;
create policy "coupons_admin_write" on public.coupons for all
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "orders_read_own_or_admin" on public.orders;
create policy "orders_read_own_or_admin" on public.orders for select
using (user_id = auth.uid() or public.is_admin());
drop policy if exists "orders_customer_insert" on public.orders;
create policy "orders_customer_insert" on public.orders for insert
with check (user_id = auth.uid());
drop policy if exists "orders_admin_update" on public.orders;
create policy "orders_admin_update" on public.orders for update
using (public.is_admin()) with check (public.is_admin());
drop policy if exists "orders_admin_delete" on public.orders;
create policy "orders_admin_delete" on public.orders for delete
using (public.is_admin());

drop policy if exists "history_read_own_or_admin" on public.order_status_history;
create policy "history_read_own_or_admin" on public.order_status_history for select
using (
  public.is_admin() or exists (
    select 1 from public.orders
    where orders.id = order_status_history.order_id and orders.user_id = auth.uid()
  )
);

drop policy if exists "notifications_read_own_or_admin" on public.notifications;
create policy "notifications_read_own_or_admin" on public.notifications for select
using (user_id = auth.uid() or public.is_admin());
drop policy if exists "notifications_update_own_or_admin" on public.notifications;
create policy "notifications_update_own_or_admin" on public.notifications for update
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

insert into public.services (id, name, description, price, price_unit, sort_order)
values
  ('wash-fold', 'Wash & Fold', 'Everyday clothes, cleaned and neatly folded', 80, 'per bag', 1),
  ('dry-clean', 'Dry Cleaning', 'Care for suits, dresses, and delicate fabrics', 150, 'per item', 2),
  ('iron', 'Iron & Press', 'Crisp finishing for shirts and uniforms', 60, 'per set', 3),
  ('bedding', 'Bedding Care', 'Fresh cleaning for sheets and comforters', 200, 'per set', 4)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  price_unit = excluded.price_unit,
  sort_order = excluded.sort_order;

insert into public.coupons (code, title, discount_type, discount_value)
values
  ('FRESH20', '20% off your next order', 'percentage', 20),
  ('BEDDING50', '฿50 off bedding care', 'fixed', 50),
  ('FREEPICKUP', 'Free pickup and delivery', 'free_pickup', 0)
on conflict (code) do update set
  title = excluded.title,
  discount_type = excluded.discount_type,
  discount_value = excluded.discount_value;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notifications'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end $$;

-- After creating owner@supershine.app in Authentication > Users, run:
-- update public.profiles set role = 'admin' where email = 'owner@supershine.app';
