'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { calculateOrderPreview, formatDateTime, isSlotAvailable, type PaymentMethod } from '@supershine/shared';
import { useMemo, useState, type FormEvent } from 'react';
import { AppShell } from '@/components/shell';
import { PriceBreakdown } from '@/components/price-breakdown';
import { Card, EmptyState, Field, PageHeader } from '@/components/ui';
import { useWebApp } from '@/context/web-app';

const names = ['Address', 'Pickup', 'Payment', 'Review'];

export default function CheckoutPage() {
  const app = useWebApp(); const router = useRouter(); const [step, setStep] = useState(1);
  const [addressId, setAddressId] = useState(app.addresses.find((item) => item.isPrimary)?.id ?? app.addresses[0]?.id ?? '');
  const [slotId, setSlotId] = useState(''); const [instructions, setInstructions] = useState('');
  const [phone, setPhone] = useState(app.profile?.phone ?? ''); const [payment, setPayment] = useState<PaymentMethod>(app.profile?.defaultPaymentMethod ?? 'cash_delivery');
  const [couponCode, setCouponCode] = useState(''); const [comment, setComment] = useState('');
  const coupon = app.coupons.find((item) => item.code === couponCode); const preview = useMemo(() => calculateOrderPreview(app.cart, app.services, app.settings, coupon), [app.cart, app.services, app.settings, coupon]);
  const canContinue = step === 1 ? Boolean(addressId) : step === 2 ? Boolean(slotId && phone.trim()) : true;
  async function submit(event: FormEvent) { event.preventDefault(); if (step < 4) { if (canContinue) setStep((value) => value + 1); return; } const order = await app.placeOrder({ addressId, pickupSlotId: slotId, pickupInstructions: instructions, contactPhone: phone, paymentMethod: payment, couponCode: couponCode || undefined, customerComment: comment }); if (order) router.push(`/orders/${order.databaseId}`); }
  if (!app.cart.length) return <AppShell><PageHeader title="Checkout"/><EmptyState title="Your cart is empty" body="Add a service before starting checkout." action={<Link className="button button-primary" href="/services">Browse services</Link>}/></AppShell>;
  return <AppShell><PageHeader eyebrow={`Step ${step} of 4`} title="Checkout" description="Your final order is calculated and validated by Super Shine before it is saved."/><div className="checkout-steps" aria-label={`Checkout step ${step} of 4`}>{names.map((name, index) => <div key={name} className={`checkout-step ${step === index + 1 ? 'active' : ''}`}>{index + 1}. {name}</div>)}</div><form className="split-layout" onSubmit={submit}><Card className="checkout-form stack">
    {step === 1 ? <><h2>Choose a pickup address</h2>{app.addresses.length ? <div className="choice-list">{app.addresses.map((address) => <label className="choice-card" key={address.id}><input type="radio" name="address" checked={addressId === address.id} onChange={() => setAddressId(address.id)}/><span><strong>{address.label}</strong><span className="muted small">{address.detail}</span></span></label>)}</div> : <EmptyState title="No saved addresses" body="Add an address from your profile, then return to checkout." action={<Link className="button button-secondary" href="/profile">Add address</Link>}/>}<p className="muted small">Delivery will return to this address unless the laundry team confirms another arrangement.</p></> : null}
    {step === 2 ? <><h2>Select your pickup</h2><div className="choice-list">{app.slots.filter(isSlotAvailable).map((slot) => <label className="choice-card" key={slot.id}><input type="radio" name="slot" checked={slotId === slot.id} onChange={() => setSlotId(slot.id)}/><span><strong>{formatDateTime(`${slot.date}T${slot.startTime}`, app.language)}</strong><span className="muted small">{slot.startTime.slice(0,5)}–{slot.endTime.slice(0,5)} · {slot.capacity - slot.bookedCount} spaces</span></span></label>)}</div><Field label="Contact phone"><input type="tel" inputMode="tel" autoComplete="tel" value={phone} onChange={(e) => setPhone(e.target.value)} required/></Field><Field label="Pickup instructions" hint="Optional · 500 characters maximum"><textarea maxLength={500} value={instructions} onChange={(e) => setInstructions(e.target.value)}/></Field></> : null}
    {step === 3 ? <><h2>Payment and offers</h2><div className="choice-list">{([['cash_pickup', 'Cash on pickup', 'Cash is due when you collect the finished laundry.'], ['cash_delivery', 'Cash on delivery', 'Cash is due when the laundry returns to your door.'], ['promptpay', 'PromptPay', 'Payment instructions appear after the final price is confirmed.']] as const).map(([value, title, body]) => <label className="choice-card" key={value}><input type="radio" name="payment" checked={payment === value} onChange={() => setPayment(value)}/><span><strong>{title}</strong><span className="muted small">{body}</span></span></label>)}</div><Field label="Coupon"><select value={couponCode} onChange={(e) => setCouponCode(e.target.value)}><option value="">No coupon</option>{app.coupons.map((item) => <option value={item.code} key={item.code}>{item.code} · {item.title}</option>)}</select></Field></> : null}
    {step === 4 ? <><h2>Review your order</h2><div className="detail-list"><div className="detail-row"><span>Address</span><strong>{app.addresses.find((item) => item.id === addressId)?.detail}</strong></div><div className="detail-row"><span>Pickup</span><strong>{app.slots.find((item) => item.id === slotId)?.date} · {app.slots.find((item) => item.id === slotId)?.startTime.slice(0,5)}</strong></div><div className="detail-row"><span>Payment</span><strong>{payment.replaceAll('_', ' ')}</strong></div><div className="detail-row"><span>Services</span><strong>{app.cart.map((line) => `${app.services.find((item) => item.id === line.serviceId)?.name} × ${line.quantity}`).join(', ')}</strong></div></div><Field label="Customer order note" hint="Optional · visible to the laundry team · 1,000 characters maximum"><textarea maxLength={1000} value={comment} onChange={(e) => setComment(e.target.value)}/></Field>{app.error ? <div className="form-error" role="alert">{app.error}</div> : null}</> : null}
    <div className="checkout-actions">{step > 1 ? <button type="button" className="button button-secondary" onClick={() => setStep((value) => value - 1)}>Back</button> : <Link className="button button-secondary" href="/cart">Back to cart</Link>}<button className="button button-primary" disabled={!canContinue || Boolean(app.busy)}>{app.busy === 'place-order' ? 'Placing order…' : step === 4 ? 'Place order' : 'Continue'}</button></div>
  </Card><Card><PriceBreakdown preview={preview} language={app.language}/><div style={{padding: '0 24px 24px'}}><p className="muted small">Estimated pricing may change after inspection. You will be asked to approve any changed final price before payment.</p></div></Card></form></AppShell>;
}
