'use client';

import { useRouter } from 'next/navigation';
import { useEffect, useState, type FormEvent } from 'react';
import type { PaymentMethod } from '@supershine/shared';
import { AppShell } from '@/components/shell';
import { Card, Field, PageHeader, StatusBadge } from '@/components/ui';
import { useWebApp } from '@/context/web-app';
import { disconnectLine, emptyLineConnection, getLineConnection, startLineConnection, updateLinePreferences, type LineConnection } from '@/lib/line';

export default function ProfilePage() {
  const app = useWebApp(); const router = useRouter();
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [payment, setPayment] = useState<PaymentMethod>('cash_delivery');
  const [label, setLabel] = useState('Home'); const [detail, setDetail] = useState(''); const [primary, setPrimary] = useState(true);
  useEffect(() => { if (app.profile) { setName(app.profile.name); setPhone(app.profile.phone); setPayment(app.profile.defaultPaymentMethod); } }, [app.profile]);
  async function saveProfile(event: FormEvent) { event.preventDefault(); await app.saveProfile({ name, phone, paymentMethod: payment }); }
  async function saveAddress(event: FormEvent) { event.preventDefault(); if (await app.saveAddress({ label, detail, primary })) { setDetail(''); setPrimary(false); } }
  async function logout() { await app.signOut(); router.replace('/'); }
  const initial = app.profile?.name?.trim().charAt(0).toUpperCase() || 'S';
  return <AppShell><PageHeader eyebrow="Your account" title="Profile and addresses" description="Account information is shared with the Super Shine mobile app."/><div className="split-layout"><div className="stack"><Card className="card-pad"><h2>Personal information</h2><form className="stack" onSubmit={saveProfile}><Field label="Full name"><input autoComplete="name" value={name} onChange={(e) => setName(e.target.value)} required/></Field><Field label="Email" hint="Email changes are managed through account support."><input type="email" value={app.profile?.email ?? ''} disabled/></Field><Field label="Phone"><input type="tel" inputMode="tel" autoComplete="tel" value={phone} onChange={(e) => setPhone(e.target.value)}/></Field><Field label="Default payment method"><select value={payment} onChange={(e) => setPayment(e.target.value as PaymentMethod)}><option value="cash_pickup">Cash on pickup</option><option value="cash_delivery">Cash on delivery</option><option value="promptpay">PromptPay</option></select></Field><button className="button button-primary" disabled={Boolean(app.busy)}>{app.busy === 'profile' ? 'Saving…' : 'Save profile'}</button></form></Card><Card className="card-pad"><h2>Saved addresses</h2><div className="stack">{app.addresses.map((address) => <div className="address-card" key={address.id}><div><strong>{address.label}</strong><p>{address.detail}</p></div>{address.isPrimary ? <StatusBadge tone="success">Primary</StatusBadge> : null}</div>)}</div><div className="divider"/><h3>Add an address</h3><form className="stack" onSubmit={saveAddress}><Field label="Label"><input maxLength={40} value={label} onChange={(e) => setLabel(e.target.value)} required/></Field><Field label="Full pickup address"><textarea maxLength={500} value={detail} onChange={(e) => setDetail(e.target.value)} required/></Field><label className="checkbox-row"><input type="checkbox" checked={primary} onChange={(e) => setPrimary(e.target.checked)}/>Make this the primary address</label><button className="button button-secondary" disabled={Boolean(app.busy)}>{app.busy === 'address' ? 'Saving…' : 'Add address'}</button></form></Card><LinePreferences demo={app.mode === 'demo'} /></div><aside className="stack"><Card className="profile-summary"><div className="avatar">{initial}</div><h2>{app.profile?.name || 'Customer'}</h2><p>{app.profile?.email || 'Demo account'}</p><StatusBadge tone={app.mode === 'demo' ? 'attention' : 'success'}>{app.mode === 'demo' ? 'Demo customer' : 'Customer account'}</StatusBadge></Card><Card className="card-pad stack"><h2>Account controls</h2><button className="button button-danger button-block" onClick={() => void logout()}>{app.mode === 'demo' ? 'Exit demo' : 'Log out'}</button></Card></aside></div></AppShell>;
}

function LinePreferences({ demo }: { demo: boolean }) {
  const [connection, setConnection] = useState<LineConnection>(emptyLineConnection());
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const refresh = async () => { if (demo) return; try { setConnection(await getLineConnection()); } catch { setMessage('LINE status is temporarily unavailable.'); } };
  useEffect(() => { void refresh(); }, [demo]);
  useEffect(() => {
    if (typeof window === 'undefined' || demo) return;
    const params = new URLSearchParams(window.location.search); const callbackAttempt = params.get('attemptId'); if (params.get('line') !== 'success' || !callbackAttempt) return;
    sessionStorage.removeItem('supershine.line.attempt'); sessionStorage.removeItem('supershine.line.secret'); setMessage('LINE connected.'); void refresh();
  }, [demo]);
  const connect = async () => { setBusy(true); setMessage(''); try { const started = await startLineConnection(); sessionStorage.setItem('supershine.line.attempt', started.attemptId); sessionStorage.setItem('supershine.line.secret', started.finalizeSecret); window.location.assign(started.authorizeUrl); } catch (error) { setMessage(error instanceof Error ? error.message : 'LINE connection failed.'); setBusy(false); } };
  const disconnect = async () => { setBusy(true); try { await disconnectLine(); setConnection(emptyLineConnection()); setMessage('LINE disconnected.'); } catch { setMessage('LINE could not be disconnected.'); } finally { setBusy(false); } };
  const setPreference = async (key: keyof Pick<LineConnection, 'notificationsEnabled' | 'orderUpdatesEnabled' | 'paymentUpdatesEnabled'>, value: boolean) => { const next = { ...connection, [key]: value }; setConnection(next); try { await updateLinePreferences(next); } catch { setConnection(connection); setMessage('LINE setting could not be saved.'); } };
  return <Card className="card-pad"><div className="line-preferences-head"><div><h2>LINE</h2><p>{demo ? 'Connect LINE from a real customer account.' : connection.connected ? connection.friendStatus === 'blocked' ? 'Connected · add Super Shine as a LINE friend' : 'Connected ✓' : 'Not connected'}</p></div>{!demo && !connection.connected ? <button className="button button-primary" onClick={() => void connect()} disabled={busy}>Connect LINE</button> : null}</div>{!demo && connection.connected ? <div className="stack"><label className="checkbox-row"><input type="checkbox" checked={connection.notificationsEnabled} onChange={(e) => void setPreference('notificationsEnabled', e.target.checked)}/>LINE notifications</label><label className="checkbox-row"><input type="checkbox" checked={connection.orderUpdatesEnabled} onChange={(e) => void setPreference('orderUpdatesEnabled', e.target.checked)}/>Order updates</label><label className="checkbox-row"><input type="checkbox" checked={connection.paymentUpdatesEnabled} onChange={(e) => void setPreference('paymentUpdatesEnabled', e.target.checked)}/>Payment updates</label><button className="button button-secondary" onClick={() => void disconnect()} disabled={busy}>Disconnect LINE</button></div> : null}{message ? <p className="form-error" role="status">{message}</p> : null}</Card>;
}
