'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useState, type FormEvent } from 'react';
import { formatDateTime, formatMoney, ORDER_STATUS_LABELS, ORDER_STATUS_PROGRESS, PAYMENT_STATUS_LABELS } from '@supershine/shared';
import { AppShell } from '@/components/shell';
import { Card, EmptyState, LoadingState, PageHeader, StatusBadge } from '@/components/ui';
import { useWebApp } from '@/context/web-app';

export default function OrderDetailPage() {
  const app = useWebApp(); const params = useParams<{ id: string }>(); const order = app.orders.find((item) => item.databaseId === decodeURIComponent(params.id));
  const [message, setMessage] = useState(''); const [uploadingFile, setUploadingFile] = useState<File | null>(null);
  async function send(event: FormEvent) { event.preventDefault(); if (await app.sendMessage(order!.databaseId, message)) setMessage(''); }
  if (app.accountLoading) return <AppShell><LoadingState label="Loading order details…"/></AppShell>;
  if (!order) return <AppShell><EmptyState title="Order not found" body="The link may be incorrect, or this order does not belong to your account." action={<Link className="button button-secondary" href="/orders">Return to orders</Link>}/></AppShell>;
  const paid = order.paymentStatus === 'paid' || order.paymentStatus === 'verified';
  return <AppShell><PageHeader eyebrow="Order tracking" title={order.id} description={`Placed ${formatDateTime(order.createdAt, app.language)}`} action={<div className="cluster"><StatusBadge tone="info">{ORDER_STATUS_LABELS[order.status]}</StatusBadge><StatusBadge tone={paid ? 'success' : order.paymentStatus === 'rejected' || order.paymentStatus === 'outstanding' ? 'danger' : 'attention'}>{PAYMENT_STATUS_LABELS[order.paymentStatus]}</StatusBadge></div>}/><Card className="detail-header"><div className="detail-title-row"><div><h1>{ORDER_STATUS_LABELS[order.status]}</h1><p className="muted">{ORDER_STATUS_PROGRESS[order.status]}% of the operational workflow complete</p></div><div className="order-amount">{formatMoney(order.amount, app.language)}</div></div><div className="progress"><span style={{width: `${Math.max(3, ORDER_STATUS_PROGRESS[order.status])}%`}}/></div>{order.priceApprovalStatus === 'pending' ? <div className="card card-pad" style={{marginTop: 20}}><h2>Final price approval required</h2><p>The laundry team updated the final total to <strong>{formatMoney(order.amount, app.language)}</strong>. Approve it to continue, or reject it so the team can contact you.</p><div className="cluster"><button className="button button-primary" disabled={Boolean(app.busy)} onClick={() => void app.respondToPrice(order.databaseId, true)}>Approve final price</button><button className="button button-danger" disabled={Boolean(app.busy)} onClick={() => void app.respondToPrice(order.databaseId, false)}>Reject</button></div></div> : null}</Card>
    <div className="grid grid-2" style={{marginTop: 20}}><Card className="detail-section"><h2>Pickup and delivery</h2><div className="detail-list"><div className="detail-row"><span>Pickup window</span><strong>{order.pickupDate} · {order.pickupStart?.slice(0,5)}–{order.pickupEnd?.slice(0,5)}</strong></div><div className="detail-row"><span>Address</span><strong>{order.pickupAddress}</strong></div><div className="detail-row"><span>Contact</span><strong>{order.contactPhone}</strong></div>{order.pickupInstructions ? <div className="detail-row"><span>Instructions</span><strong>{order.pickupInstructions}</strong></div> : null}</div></Card><Card className="detail-section"><h2>Payment</h2><div className="detail-list"><div className="detail-row"><span>Method</span><strong>{order.paymentMethod.replaceAll('_', ' ')}</strong></div><div className="detail-row"><span>Status</span><strong>{PAYMENT_STATUS_LABELS[order.paymentStatus]}</strong></div><div className="detail-row"><span>Amount</span><strong>{formatMoney(order.amount, app.language)}</strong></div></div>{order.paymentRejectionReason ? <div className="form-error">Payment was rejected: {order.paymentRejectionReason}</div> : null}{order.paymentMethod === 'promptpay' && !paid ? <div className="stack" style={{marginTop: 16}}><p className="muted small">Upload a JPG, PNG, or WebP payment slip after the final price is approved.</p><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setUploadingFile(event.target.files?.[0] ?? null)}/><button className="button button-primary" disabled={!uploadingFile || Boolean(app.busy)} onClick={() => uploadingFile && void app.uploadPaymentSlip(order.databaseId, uploadingFile)}>Submit payment slip</button></div> : null}</Card></div>
    <div className="grid grid-2" style={{marginTop: 20}}><Card className="detail-section"><h2>Service items</h2><div className="detail-list">{order.items.map((item) => <div className="detail-row" key={item.id}><span>{item.serviceName} × {item.quantity} {item.priceUnit}</span><strong>{formatMoney(item.lineTotal, app.language)}</strong></div>)}<div className="detail-row"><span>Pickup fee</span><strong>{formatMoney(order.pickupFee, app.language)}</strong></div><div className="detail-row"><span>Delivery fee</span><strong>{formatMoney(order.deliveryFee, app.language)}</strong></div>{order.discount ? <div className="detail-row"><span>Discount{order.couponCode ? ` · ${order.couponCode}` : ''}</span><strong>−{formatMoney(order.discount, app.language)}</strong></div> : null}</div>{order.customerComment ? <><div className="divider"/><h2>Customer order note</h2><p style={{whiteSpace: 'pre-wrap'}}>{order.customerComment}</p></> : null}</Card><Card className="detail-section"><h2>Status timeline</h2><div className="timeline">{order.history.map((item) => <div className="timeline-item" key={item.id}><strong>{ORDER_STATUS_LABELS[item.newStatus]}</strong>{item.comment ? <span className="small">{item.comment}</span> : null}<time>{formatDateTime(item.createdAt, app.language)}</time></div>)}</div></Card></div>
    <Card className="detail-section" style={{marginTop: 20} as never}><h2>Conversation with Super Shine</h2><div className="messages">{order.messages.length ? order.messages.map((item) => <div className={`message ${item.senderRole}`} key={item.id}><strong>{item.senderRole === 'admin' ? 'Super Shine' : 'You'}</strong><div>{item.message}</div><small>{formatDateTime(item.createdAt, app.language)}</small></div>) : <p className="muted">No messages yet. Your original checkout note remains separate above.</p>}</div><form className="message-form" onSubmit={send}><input aria-label="Message" maxLength={1000} placeholder="Write a message about this order" value={message} onChange={(e) => setMessage(e.target.value)}/><button className="button button-primary" disabled={!message.trim() || Boolean(app.busy)}>Send</button></form></Card>
  </AppShell>;
}
