import { router as expoRouter } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { AdminCard, StatusBadge } from '@/admin/admin-ui';
import { Button } from '@/components/super-ui';
import { Colors, FontFamily, FontFamilyMedium } from '@/constants/design';
import { formatBangkokDate } from '@/lib/domain';
import { supabase } from '@/lib/supabase';
import { mapDriverTask, type DriverSummary, type DriverTask } from '@/types/driver';

const TONE={unassigned:'amber',assigned:'blue',accepted:'blue',en_route:'teal',arrived:'teal',completed:'green',cancelled:'gray',failed:'coral'} as const;
const router = expoRouter as { push: (href: string) => void };

export function AdminDriverTaskCard({orderId,onChanged}:{orderId:string;onChanged?:()=>void}){const[tasks,setTasks]=useState<DriverTask[]>([]);const[drivers,setDrivers]=useState<DriverSummary[]>([]);const[busy,setBusy]=useState('');const[reason,setReason]=useState('');const[error,setError]=useState('');
  const load=useCallback(async()=>{if(!supabase)return;const[taskResult,driverResult]=await Promise.all([supabase.rpc('admin_order_driver_tasks_v1',{p_order_id:orderId}),supabase.rpc('admin_drivers_list_v1')]);if(taskResult.error||driverResult.error){setError((taskResult.error||driverResult.error)?.message||'Driver details could not load.');return;}setTasks(((taskResult.data||[]) as Record<string,unknown>[]).map(mapDriverTask));setDrivers(((driverResult.data||[]) as Record<string,unknown>[]).map((row)=>({id:String(row.id),name:String(row.name||''),email:String(row.email||''),phone:String(row.phone||''),activeTaskCount:Number(row.activeTaskCount||0)})));},[orderId]);
  useEffect(()=>{void load();if(!supabase)return;const client=supabase;const channel=client.channel(`admin-order-driver:${orderId}`).on('postgres_changes',{event:'*',schema:'public',table:'driver_tasks',filter:`order_id=eq.${orderId}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'driver_task_issues',filter:`order_id=eq.${orderId}`},()=>void load()).subscribe();return()=>{void client.removeChannel(channel);};},[load,orderId]);
  async function assign(task:DriverTask,driverId:string){if(!supabase||busy)return;if(task.driverId&&task.driverId!==driverId&&reason.trim().length<3){setError('Enter a reassignment reason first.');return;}setBusy(task.id);setError('');const result=await supabase.rpc('admin_assign_driver_task_v1',{p_task_id:task.id,p_driver_id:driverId,p_reason:reason.trim()});setBusy('');if(result.error){setError(result.error.message);return;}setReason('');await load();onChanged?.();}
  async function reset(task:DriverTask){if(!supabase||busy)return;if(reason.trim().length<3){setError('Enter an override reason first.');return;}setBusy(task.id);setError('');const result=await supabase.rpc('admin_reset_driver_task_v1',{p_task_id:task.id,p_reason:reason.trim()});setBusy('');if(result.error){setError(result.error.message);return;}setReason('');await load();onChanged?.();}
  async function completeOverride(task:DriverTask){if(!supabase||busy)return;if(reason.trim().length<3){setError('Enter an emergency override reason first.');return;}setBusy(task.id);setError('');const result=await supabase.rpc('admin_complete_driver_task_v1',{p_task_id:task.id,p_reason:reason.trim()});setBusy('');if(result.error){setError(result.error.message);return;}setReason('');await load();onChanged?.();}
  if(!tasks.length)return null;return <AdminCard style={styles.card}><Text style={styles.title}>Driver trips</Text><Text style={styles.hint}>Assign each home pickup or delivery leg. The driver’s action updates the customer order.</Text>{error?<Text style={styles.error}>{error}</Text>:null}{tasks.map((task)=><View key={task.id} style={styles.task}><View style={styles.taskHead}><View><Text style={styles.taskTitle}>{task.taskType==='pickup'?'Home pickup':'Home delivery'}</Text><Text style={styles.meta}>{task.scheduledFor?formatBangkokDate(task.scheduledFor):'Schedule follows the order'}</Text></View><StatusBadge label={task.taskStatus.replace('_',' ')} tone={TONE[task.taskStatus]}/></View><Text style={styles.driver}>{task.driverName||'No driver assigned'}</Text>{task.openIssue?<View style={styles.issue}><Text style={styles.issueTitle}>{task.openIssue.reason}</Text><Text style={styles.meta}>{task.openIssue.notes||'Driver requested admin help.'}</Text></View>:null}{task.driverId?<TextInput value={reason} onChangeText={setReason} placeholder={task.taskStatus==='failed'?'Reason required to retry or override':'Reason required to reassign or override'} placeholderTextColor={Colors.textMuted} style={styles.input}/>:null}<View style={styles.driverList}>{drivers.map((driver)=><Pressable key={driver.id} disabled={busy===task.id||driver.id===task.driverId} onPress={()=>void assign(task,driver.id)} style={[styles.driverChip,driver.id===task.driverId&&styles.driverChipActive]}><Text style={[styles.driverChipText,driver.id===task.driverId&&styles.driverChipTextActive]}>{driver.name||driver.email} · {driver.activeTaskCount}</Text></Pressable>)}</View>{task.taskStatus==='failed'?<Button label="Reset task for retry" variant="secondary" onPress={()=>void reset(task)} loading={busy===task.id}/>:null}{['en_route','arrived','failed'].includes(task.taskStatus)?<Button label="Emergency: confirm completed" variant="ghost" onPress={()=>void completeOverride(task)} loading={busy===task.id}/>:null}{!drivers.length?<Button label="Add a driver account" variant="secondary" onPress={()=>router.push('/admin/drivers')}/>:null}</View>)}</AdminCard>}
const styles=StyleSheet.create({card:{padding:17,gap:12,marginBottom:18},title:{color:Colors.navy,fontFamily:FontFamilyMedium,fontSize:14,fontWeight:'500'},hint:{color:Colors.textMuted,fontFamily:FontFamily,fontSize:9,lineHeight:15},error:{color:Colors.coral,fontFamily:FontFamily,fontSize:10},task:{borderTopWidth:1,borderTopColor:Colors.line,paddingTop:13,gap:9},taskHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},taskTitle:{color:Colors.navy,fontFamily:FontFamilyMedium,fontSize:11.5,fontWeight:'500'},meta:{color:Colors.textMuted,fontFamily:FontFamily,fontSize:8.5,lineHeight:14,marginTop:3},driver:{color:Colors.tealDark,fontFamily:FontFamilyMedium,fontSize:10.5,fontWeight:'500'},input:{minHeight:40,borderWidth:1,borderColor:Colors.line,borderRadius:11,paddingHorizontal:10,color:Colors.text,fontFamily:FontFamily,fontSize:9.5},driverList:{flexDirection:'row',flexWrap:'wrap',gap:6},driverChip:{borderRadius:11,backgroundColor:'#EEF3F2',paddingHorizontal:9,paddingVertical:7},driverChipActive:{backgroundColor:Colors.tealLight},driverChipText:{color:Colors.textMuted,fontFamily:FontFamilyMedium,fontSize:8.5,fontWeight:'500'},driverChipTextActive:{color:Colors.tealDark},issue:{borderRadius:11,backgroundColor:Colors.coralLight,padding:10},issueTitle:{color:Colors.coral,fontFamily:FontFamilyMedium,fontSize:10,fontWeight:'500'}});
