import { Modal, Platform, Pressable, StyleSheet, Text, View } from 'react-native';

import { SymbolView } from '@/components/symbol';
import { CustomerColors as C, CustomerHeight, CustomerRadius, CustomerSpace as S, CustomerType } from '@/constants/customer-design';
import { languageOptions, type LanguageCode } from '@/i18n';

export function LanguageButton({ label, onPress }: { label: string; onPress: () => void }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={styles.globe}><SymbolView name={{ ios: 'globe', android: 'language', web: 'language' }} size={21} tintColor={C.navy} /></Pressable>;
}

export function LanguagePicker({ visible, selected, title, closeLabel, onSelect, onClose }: { visible: boolean; selected: LanguageCode; title: string; closeLabel: string; onSelect: (language: LanguageCode) => void; onClose: () => void }) {
  return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable style={styles.backdrop} onPress={onClose}><Pressable accessibilityViewIsModal style={styles.sheet} onPress={() => undefined}><View style={styles.heading}><Text accessibilityRole="header" style={styles.title}>{title}</Text><Pressable accessibilityRole="button" accessibilityLabel={closeLabel} onPress={onClose} style={styles.close}><SymbolView name={{ ios: 'xmark', android: 'close', web: 'close' }} size={20} tintColor={C.navy} /></Pressable></View><View accessibilityRole="radiogroup" style={styles.list}>{languageOptions.map((item) => <Pressable key={item.code} accessibilityRole="radio" accessibilityLabel={item.name} accessibilityState={{ checked: selected === item.code }} onPress={() => { onSelect(item.code); onClose(); }} style={[styles.row, selected === item.code && styles.selected]}><View style={styles.badge}><Text style={styles.badgeText}>{item.badge}</Text></View><View style={styles.copy}><Text style={styles.native}>{item.nativeName}</Text><Text style={styles.english}>{item.name}</Text></View>{selected === item.code ? <SymbolView name={{ ios: 'checkmark.circle.fill', android: 'check_circle', web: 'check_circle' }} size={22} tintColor={C.teal} /> : null}</Pressable>)}</View></Pressable></Pressable></Modal>;
}

const styles = StyleSheet.create({ globe: { width: CustomerHeight.touch, height: CustomerHeight.touch, borderRadius: CustomerRadius.control, borderWidth: 1, borderColor: C.border, backgroundColor: C.white, alignItems: 'center', justifyContent: 'center' }, backdrop: { flex: 1, backgroundColor: 'rgba(9,29,43,0.46)', justifyContent: 'flex-end' }, sheet: { width: '100%', maxWidth: Platform.OS === 'web' ? 430 : 560, alignSelf: 'center', backgroundColor: C.white, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: S.xl, paddingBottom: S.xxl }, heading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: S.lg }, title: { ...CustomerType.section, color: C.navy }, close: { width: CustomerHeight.touch, height: CustomerHeight.touch, alignItems: 'center', justifyContent: 'center' }, list: { gap: S.sm }, row: { minHeight: 60, borderWidth: 1, borderColor: C.border, borderRadius: CustomerRadius.control, paddingHorizontal: S.md, flexDirection: 'row', alignItems: 'center', gap: S.md }, selected: { borderWidth: 2, borderColor: C.teal, backgroundColor: C.mint }, badge: { width: 38, height: 38, borderRadius: 12, backgroundColor: C.navy, alignItems: 'center', justifyContent: 'center' }, badgeText: { color: C.white, fontSize: 11, fontWeight: '900' }, copy: { flex: 1 }, native: { color: C.text, fontSize: 15, fontWeight: '800' }, english: { ...CustomerType.caption, color: C.muted } });
