import { StyleSheet, Text, View } from 'react-native';

import { Card, IconBadge } from '@/components/super-ui';
import { Colors, FontFamily, FontFamilyMedium, Space } from '@/constants/design';
import { useCustomerDriverTasks } from '@/hooks/use-customer-driver-tasks';

export function CustomerDriverTaskCard({orderId,status}:{orderId:string;status:string}){const{tasks}=useCustomerDriverTasks(orderId);const phase=status==='pickup_in_progress'||status==='accepted'?'pickup':status==='ready'||status==='out_for_delivery'?'delivery':null;const task=tasks.find((item)=>item.taskType===phase&& !['cancelled','completed'].includes(item.taskStatus));if(!task||task.taskStatus==='unassigned')return null;const active=['en_route','arrived'].includes(task.taskStatus);return <Card style={[styles.card,active&&styles.cardActive]}><View style={styles.row}><IconBadge name={{ios:'person.crop.circle.fill',android:'account_circle',web:'account_circle'}} badgeSize={44} size={21}/><View style={styles.copy}><Text style={styles.eyebrow}>{task.taskType==='pickup'?'PICKUP DRIVER':'DELIVERY DRIVER'}</Text><Text style={styles.title}>{task.driverName||'Super Shine driver'}</Text><Text style={styles.state}>{task.taskStatus==='assigned'?'Assignment confirmed':task.taskStatus==='accepted'?'Driver is preparing':task.taskStatus==='en_route'?'On the way to you':task.taskStatus==='arrived'?'Driver has arrived':'Trip update'}</Text></View>{active?<View style={styles.live}><View style={styles.dot}/><Text style={styles.liveText}>LIVE</Text></View>:null}</View>{task.verificationCode?<View style={styles.codeRow}><View><Text style={styles.codeLabel}>{task.taskType==='pickup'?'PICKUP CODE':'DELIVERY CODE'}</Text><Text style={styles.codeHint}>Tell this code to the driver only when you hand over or receive your laundry.</Text></View><Text selectable style={styles.code}>{task.verificationCode}</Text></View>:null}</Card>}
const styles=StyleSheet.create({card:{padding:Space.lg,marginTop:Space.md,borderWidth:1,borderColor:Colors.line},cardActive:{borderColor:Colors.teal},row:{flexDirection:'row',alignItems:'center',gap:11},copy:{flex:1},eyebrow:{color:Colors.tealDark,fontFamily:FontFamilyMedium,fontSize:9,fontWeight:'500',letterSpacing:.8},title:{color:Colors.navy,fontFamily:FontFamilyMedium,fontSize:14,fontWeight:'500',marginTop:3},state:{color:Colors.textMuted,fontFamily:FontFamily,fontSize:10.5,marginTop:3},live:{borderRadius:13,backgroundColor:Colors.successLight,paddingHorizontal:9,paddingVertical:6,flexDirection:'row',alignItems:'center',gap:5},dot:{width:6,height:6,borderRadius:3,backgroundColor:Colors.success},liveText:{color:Colors.success,fontFamily:FontFamilyMedium,fontSize:8,fontWeight:'500'},codeRow:{marginTop:13,borderRadius:14,backgroundColor:Colors.tealLight,padding:12,flexDirection:'row',alignItems:'center',gap:12},codeLabel:{color:Colors.tealDark,fontFamily:FontFamilyMedium,fontSize:9,fontWeight:'500',letterSpacing:.7},codeHint:{maxWidth:430,color:Colors.textMuted,fontFamily:FontFamily,fontSize:9,lineHeight:14,marginTop:3},code:{marginLeft:'auto',color:Colors.navy,fontFamily:FontFamilyMedium,fontSize:23,fontWeight:'500',letterSpacing:3}});

