begin;

-- Driver work is deliberately modelled separately from the laundry order.
-- Orders describe the customer's laundry journey; tasks describe one employee trip.
create table if not exists public.driver_tasks (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  driver_id uuid references public.profiles(id) on delete set null,
  task_type text not null check (task_type in ('pickup', 'delivery')),
  task_status text not null default 'unassigned' check (task_status in (
    'unassigned', 'assigned', 'accepted', 'en_route', 'arrived',
    'completed', 'cancelled', 'failed'
  )),
  scheduled_for timestamptz,
  assigned_at timestamptz,
  accepted_at timestamptz,
  started_at timestamptz,
  arrived_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint driver_tasks_order_leg_unique unique (order_id, task_type)
);

create index if not exists driver_tasks_driver_queue_idx
  on public.driver_tasks(driver_id, task_status, scheduled_for, created_at);
create index if not exists driver_tasks_admin_queue_idx
  on public.driver_tasks(task_status, scheduled_for, created_at);

-- Codes are isolated from driver-readable task rows. Drivers can submit a code
-- to the completion RPC, but cannot query the expected value.
create table if not exists public.driver_task_verifications (
  task_id uuid primary key references public.driver_tasks(id) on delete cascade,
  verification_code text not null check (verification_code ~ '^[0-9]{4}$'),
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  locked_until timestamptz,
  verified_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.driver_task_events (
  id bigint generated by default as identity primary key,
  task_id uuid not null references public.driver_tasks(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  actor_role text not null check (actor_role in ('admin', 'driver', 'customer', 'system')),
  action text not null,
  previous_status text,
  new_status text,
  reason text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists driver_task_events_task_created_idx
  on public.driver_task_events(task_id, created_at desc);

create table if not exists public.driver_task_issues (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.driver_tasks(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  driver_id uuid not null references public.profiles(id) on delete restrict,
  reason text not null,
  notes text not null default '',
  status text not null default 'open' check (status in ('open', 'resolved')),
  resolved_by uuid references public.profiles(id) on delete set null,
  resolution_note text not null default '',
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists driver_task_issues_admin_queue_idx
  on public.driver_task_issues(status, created_at desc);

alter table public.order_live_locations
  add column if not exists task_id uuid references public.driver_tasks(id) on delete set null;
create index if not exists order_live_locations_task_idx
  on public.order_live_locations(task_id) where task_id is not null;

create or replace function public.is_driver()
returns boolean language sql stable security definer set search_path = public, pg_temp as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'driver');
$$;
revoke all on function public.is_driver() from public, anon;
grant execute on function public.is_driver() to authenticated;

-- Client profile writes may change contact/preferences, never privileges.
-- Server-side service-role provisioning has no auth.uid() and remains available.
create or replace function public.protect_profile_role_v1()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if tg_op = 'INSERT' and coalesce(auth.jwt() ->> 'role','') <> 'service_role' then
    new.role := 'customer';
    new.is_demo := coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false);
  elsif coalesce(auth.jwt() ->> 'role','') <> 'service_role'
    and (new.role is distinct from old.role or new.is_demo is distinct from old.is_demo) then
    raise exception 'ROLE_CHANGE_FORBIDDEN';
  end if;
  return new;
end;
$$;
revoke all on function public.protect_profile_role_v1() from public, anon, authenticated;
drop trigger if exists profiles_protect_role_insert_v1 on public.profiles;
create trigger profiles_protect_role_insert_v1 before insert on public.profiles
for each row execute function public.protect_profile_role_v1();
drop trigger if exists profiles_protect_role_v1 on public.profiles;
create trigger profiles_protect_role_v1 before update of role,is_demo on public.profiles
for each row execute function public.protect_profile_role_v1();

alter table public.driver_tasks enable row level security;
alter table public.driver_task_verifications enable row level security;
alter table public.driver_task_events enable row level security;
alter table public.driver_task_issues enable row level security;

drop policy if exists "driver_tasks_participant_read_v1" on public.driver_tasks;
create policy "driver_tasks_participant_read_v1" on public.driver_tasks for select to authenticated using (
  public.is_admin() or driver_id = auth.uid() or exists (
    select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()
  )
);
drop policy if exists "driver_task_verifications_customer_admin_read_v1" on public.driver_task_verifications;
create policy "driver_task_verifications_customer_admin_read_v1" on public.driver_task_verifications for select to authenticated using (
  public.is_admin() or exists (
    select 1 from public.driver_tasks t join public.orders o on o.id = t.order_id
    where t.id = task_id and o.user_id = auth.uid()
  )
);
drop policy if exists "driver_task_events_participant_read_v1" on public.driver_task_events;
create policy "driver_task_events_participant_read_v1" on public.driver_task_events for select to authenticated using (
  public.is_admin() or exists (
    select 1 from public.driver_tasks t join public.orders o on o.id = t.order_id
    where t.id = task_id and (t.driver_id = auth.uid() or o.user_id = auth.uid())
  )
);
drop policy if exists "driver_task_issues_participant_read_v1" on public.driver_task_issues;
create policy "driver_task_issues_participant_read_v1" on public.driver_task_issues for select to authenticated using (
  public.is_admin() or driver_id = auth.uid()
);

-- Writes are transaction-only. No client role can manufacture assignments,
-- promote itself, alter task history, or bypass verification.
revoke insert, update, delete on public.driver_tasks from anon, authenticated;
revoke insert, update, delete on public.driver_task_verifications from anon, authenticated;
revoke insert, update, delete on public.driver_task_events from anon, authenticated;
revoke insert, update, delete on public.driver_task_issues from anon, authenticated;
grant select on public.driver_tasks, public.driver_task_events, public.driver_task_issues to authenticated;
grant select on public.driver_task_verifications to authenticated;

create or replace function public.driver_task_schedule_v1(p_order public.orders)
returns timestamptz language sql stable set search_path = public, pg_temp as $$
  select case
    when p_order.pickup_date is not null and p_order.pickup_start is not null then
      ((p_order.pickup_date::text || ' ' || p_order.pickup_start::text)::timestamp at time zone 'Asia/Bangkok')
    else null
  end;
$$;

create or replace function public.create_driver_task_v1(p_order_id uuid, p_task_type text)
returns uuid language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_order public.orders%rowtype;
  v_task_id uuid;
begin
  if p_task_type not in ('pickup', 'delivery') then raise exception 'INVALID_TASK_TYPE'; end if;
  select * into v_order from public.orders where id = p_order_id;
  if not found or v_order.is_demo then return null; end if;
  if p_task_type = 'pickup' and v_order.collection_method <> 'home_pickup' then return null; end if;
  if p_task_type = 'delivery' and v_order.return_method <> 'home_delivery' then return null; end if;

  insert into public.driver_tasks(order_id, task_type, scheduled_for)
  values (
    p_order_id,
    p_task_type,
    case when p_task_type = 'pickup' then public.driver_task_schedule_v1(v_order) else v_order.delivery_eta end
  )
  on conflict (order_id, task_type) do nothing
  returning id into v_task_id;

  if v_task_id is not null then
    insert into public.driver_task_verifications(task_id, verification_code)
    values (v_task_id, lpad(floor(random() * 10000)::integer::text, 4, '0'));
    insert into public.driver_task_events(task_id, order_id, actor_role, action, new_status)
    values (v_task_id, p_order_id, 'system', 'task_created', 'unassigned');
  else
    select id into v_task_id from public.driver_tasks where order_id = p_order_id and task_type = p_task_type;
  end if;
  return v_task_id;
end;
$$;
revoke all on function public.create_driver_task_v1(uuid,text) from public, anon, authenticated;

create or replace function public.sync_driver_tasks_from_order_v1()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_task_id uuid;
  v_driver_id uuid;
  v_scheduled_for timestamptz;
begin
  if new.is_demo then return new; end if;
  if new.collection_method = 'home_pickup' and new.status in (
    'accepted','pickup_in_progress','picked_up','received_at_store','processing','ready',
    'ready_for_collection','out_for_delivery','delivered','collected'
  ) then
    v_task_id := public.create_driver_task_v1(new.id, 'pickup');
  end if;
  if new.return_method = 'home_delivery' and new.status in ('ready','out_for_delivery','delivered') then
    v_task_id := public.create_driver_task_v1(new.id, 'delivery');
  end if;

  -- Keep the assigned employee's schedule in sync without creating a second task.
  if new.collection_method = 'home_pickup' then
    v_scheduled_for := public.driver_task_schedule_v1(new);
    v_task_id := null;
    v_driver_id := null;
    update public.driver_tasks set scheduled_for=v_scheduled_for,updated_at=now()
    where order_id=new.id and task_type='pickup' and task_status not in ('completed','cancelled')
      and scheduled_for is distinct from v_scheduled_for
    returning id,driver_id into v_task_id,v_driver_id;
    if v_task_id is not null and v_driver_id is not null and tg_op='UPDATE' then
      insert into public.notifications(user_id,order_id,title,body,type,link,message_params,source_event_key)
      values(v_driver_id,new.id,'Pickup schedule changed','The pickup schedule for order '||new.order_number||' was updated.',
        'driver_task_schedule_changed','/driver/task/'||v_task_id,
        jsonb_build_object('orderNumber',new.order_number,'taskType','pickup','scheduledFor',v_scheduled_for),
        'driver-task-schedule:'||v_task_id::text||':'||extract(epoch from clock_timestamp())::bigint::text)
      on conflict (user_id,order_id,source_event_key) where source_event_key is not null and order_id is not null do nothing;
    end if;
  end if;
  if new.return_method = 'home_delivery' then
    v_scheduled_for := new.delivery_eta;
    v_task_id := null;
    v_driver_id := null;
    update public.driver_tasks set scheduled_for=v_scheduled_for,updated_at=now()
    where order_id=new.id and task_type='delivery' and task_status not in ('completed','cancelled')
      and scheduled_for is distinct from v_scheduled_for
    returning id,driver_id into v_task_id,v_driver_id;
    if v_task_id is not null and v_driver_id is not null and tg_op='UPDATE' then
      insert into public.notifications(user_id,order_id,title,body,type,link,message_params,source_event_key)
      values(v_driver_id,new.id,'Delivery schedule changed','The delivery schedule for order '||new.order_number||' was updated.',
        'driver_task_schedule_changed','/driver/task/'||v_task_id,
        jsonb_build_object('orderNumber',new.order_number,'taskType','delivery','scheduledFor',v_scheduled_for),
        'driver-task-schedule:'||v_task_id::text||':'||extract(epoch from clock_timestamp())::bigint::text)
      on conflict (user_id,order_id,source_event_key) where source_event_key is not null and order_id is not null do nothing;
    end if;
  end if;
  if new.status = 'cancelled' then
    insert into public.notifications(user_id,order_id,title,body,type,link,message_params,source_event_key)
    select t.driver_id,new.id,'Driver task cancelled','The '||t.task_type||' task for order '||new.order_number||' was cancelled.',
      'driver_task_cancelled','/driver/task/'||t.id,
      jsonb_build_object('orderNumber',new.order_number,'taskType',t.task_type),
      'driver-task-cancelled:'||t.id::text
    from public.driver_tasks t
    where t.order_id=new.id and t.driver_id is not null and t.task_status not in ('completed','cancelled')
    on conflict (user_id,order_id,source_event_key) where source_event_key is not null and order_id is not null do nothing;
    update public.driver_tasks set task_status = 'cancelled', cancelled_at = now(), updated_at = now()
    where order_id = new.id and task_status not in ('completed','cancelled');
    update public.order_live_locations set status = 'completed', ended_at = now(), updated_at = now()
    where order_id = new.id and status = 'active';
  end if;
  return new;
end;
$$;
revoke all on function public.sync_driver_tasks_from_order_v1() from public, anon, authenticated;
drop trigger if exists orders_sync_driver_tasks_v1 on public.orders;
create trigger orders_sync_driver_tasks_v1 after insert or update of status, pickup_date, pickup_start, delivery_eta on public.orders
for each row execute function public.sync_driver_tasks_from_order_v1();

-- Existing live orders are made task-aware without duplicating a leg.
select public.create_driver_task_v1(id, 'pickup') from public.orders
where not is_demo and collection_method = 'home_pickup' and status in (
  'accepted','pickup_in_progress','picked_up','received_at_store','processing','ready',
  'ready_for_collection','out_for_delivery','delivered','collected'
);
select public.create_driver_task_v1(id, 'delivery') from public.orders
where not is_demo and return_method = 'home_delivery' and status in ('ready','out_for_delivery','delivered');

update public.driver_tasks t set
  driver_id = o.assigned_driver_id,
  task_status = case
    when t.task_type = 'pickup' and o.status in ('picked_up','received_at_store','processing','ready','ready_for_collection','out_for_delivery','delivered','collected') then 'completed'
    when t.task_type = 'delivery' and o.status = 'delivered' then 'completed'
    when t.task_type = 'pickup' and o.status = 'pickup_in_progress' then case when o.assigned_driver_id is null then 'unassigned' else 'en_route' end
    when t.task_type = 'delivery' and o.status = 'out_for_delivery' then case when o.assigned_driver_id is null then 'unassigned' else 'en_route' end
    when o.assigned_driver_id is not null then 'assigned'
    else t.task_status end,
  assigned_at = case when o.assigned_driver_id is not null then coalesce(t.assigned_at, now()) else t.assigned_at end,
  completed_at = case
    when (t.task_type = 'pickup' and o.status in ('picked_up','received_at_store','processing','ready','ready_for_collection','out_for_delivery','delivered','collected'))
      or (t.task_type = 'delivery' and o.status = 'delivered') then coalesce(t.completed_at, o.updated_at)
    else t.completed_at end,
  updated_at = now()
from public.orders o where o.id = t.order_id;

create or replace function public.driver_task_payload_v1(p_task_id uuid, p_include_code boolean default false)
returns jsonb language sql stable security definer set search_path = public, pg_temp as $$
  select jsonb_build_object(
    'id', t.id, 'orderId', t.order_id, 'orderNumber', o.order_number,
    'driverId', t.driver_id, 'driverName', d.full_name,
    'taskType', t.task_type, 'taskStatus', t.task_status, 'scheduledFor', t.scheduled_for,
    'assignedAt', t.assigned_at, 'acceptedAt', t.accepted_at, 'startedAt', t.started_at,
    'arrivedAt', t.arrived_at, 'completedAt', t.completed_at,
    'customerName', c.full_name, 'customerPhone', coalesce(nullif(o.contact_phone,''), c.phone),
    'address', case when t.task_type = 'pickup' then o.pickup_address else o.delivery_address end,
    'instructions', o.pickup_instructions, 'itemSummary', o.item_summary,
    'latitude', case when t.task_type = 'pickup' then o.pickup_latitude else o.delivery_latitude end,
    'longitude', case when t.task_type = 'pickup' then o.pickup_longitude else o.delivery_longitude end,
    'verificationCode', case when p_include_code then v.verification_code else null end,
    'openIssue', case when public.is_admin() or t.driver_id = auth.uid() then
      (select jsonb_build_object('id', i.id, 'reason', i.reason, 'notes', i.notes, 'createdAt', i.created_at)
        from public.driver_task_issues i where i.task_id = t.id and i.status = 'open' order by i.created_at desc limit 1)
      else null end,
    'updatedAt', t.updated_at
  )
  from public.driver_tasks t
  join public.orders o on o.id = t.order_id
  join public.profiles c on c.id = o.user_id
  left join public.profiles d on d.id = t.driver_id
  left join public.driver_task_verifications v on v.task_id = t.id
  where t.id = p_task_id;
$$;
revoke all on function public.driver_task_payload_v1(uuid,boolean) from public, anon, authenticated;

create or replace function public.driver_tasks_list_v1(p_history boolean default false)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_result jsonb;
begin
  if not public.is_driver() then raise exception 'DRIVER_REQUIRED'; end if;
  select coalesce(jsonb_agg(public.driver_task_payload_v1(t.id, false) order by
    case when t.task_status in ('en_route','arrived') then 0 when t.task_status in ('assigned','accepted') then 1 else 2 end,
    t.scheduled_for nulls last, t.created_at), '[]'::jsonb)
  into v_result from public.driver_tasks t
  where t.driver_id = auth.uid()
    and (case when p_history then t.task_status in ('completed','cancelled')
      else t.task_status in ('assigned','accepted','en_route','arrived','failed') end);
  return v_result;
end;
$$;

create or replace function public.driver_task_detail_v1(p_task_id uuid)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not public.is_driver() or not exists (
    select 1 from public.driver_tasks where id = p_task_id and driver_id = auth.uid()
  ) then raise exception 'DRIVER_TASK_NOT_FOUND'; end if;
  return public.driver_task_payload_v1(p_task_id, false);
end;
$$;

create or replace function public.customer_order_driver_tasks_v1(p_order_id uuid)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_result jsonb;
begin
  if auth.uid() is null or not exists (
    select 1 from public.orders where id = p_order_id and user_id = auth.uid()
  ) then raise exception 'ORDER_NOT_FOUND'; end if;
  select coalesce(jsonb_agg(public.driver_task_payload_v1(t.id, true) order by t.created_at), '[]'::jsonb)
  into v_result from public.driver_tasks t where t.order_id = p_order_id;
  return v_result;
end;
$$;

create or replace function public.admin_order_driver_tasks_v1(p_order_id uuid)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_result jsonb;
begin
  if not public.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  select coalesce(jsonb_agg(public.driver_task_payload_v1(t.id, true) order by t.created_at), '[]'::jsonb)
  into v_result from public.driver_tasks t where t.order_id = p_order_id;
  return v_result;
end;
$$;

create or replace function public.admin_drivers_list_v1()
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_result jsonb;
begin
  if not public.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', p.id, 'name', p.full_name, 'email', p.email, 'phone', p.phone,
    'activeTaskCount', (select count(*) from public.driver_tasks t where t.driver_id = p.id and t.task_status in ('assigned','accepted','en_route','arrived'))
  ) order by p.full_name, p.email), '[]'::jsonb) into v_result
  from public.profiles p where p.role = 'driver';
  return v_result;
end;
$$;

create or replace function public.admin_driver_operations_v1()
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_result jsonb;
begin
  if not public.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  select jsonb_build_object(
    'drivers', public.admin_drivers_list_v1(),
    'tasks', coalesce((select jsonb_agg(public.driver_task_payload_v1(t.id, true) order by
      case when t.task_status = 'unassigned' then 0 when exists(select 1 from public.driver_task_issues i where i.task_id=t.id and i.status='open') then 1 else 2 end,
      t.scheduled_for nulls last, t.created_at)
      from public.driver_tasks t where t.task_status not in ('completed','cancelled')), '[]'::jsonb),
    'issues', coalesce((select jsonb_agg(jsonb_build_object(
      'id', i.id, 'taskId', i.task_id, 'orderId', i.order_id, 'orderNumber', o.order_number,
      'driverId', i.driver_id, 'driverName', p.full_name, 'reason', i.reason,
      'notes', i.notes, 'status', i.status, 'createdAt', i.created_at
    ) order by i.created_at desc) from public.driver_task_issues i
      join public.orders o on o.id=i.order_id join public.profiles p on p.id=i.driver_id
      where i.status='open'), '[]'::jsonb)
  ) into v_result;
  return v_result;
end;
$$;

create or replace function public.admin_assign_driver_task_v1(
  p_task_id uuid, p_driver_id uuid, p_reason text default ''
) returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_task public.driver_tasks%rowtype; v_old_driver uuid;
begin
  if not public.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if not exists(select 1 from public.profiles where id=p_driver_id and role='driver') then raise exception 'DRIVER_NOT_FOUND'; end if;
  select * into v_task from public.driver_tasks where id=p_task_id for update;
  if not found then raise exception 'TASK_NOT_FOUND'; end if;
  if v_task.task_status in ('completed','cancelled') then raise exception 'TASK_CLOSED'; end if;
  v_old_driver := v_task.driver_id;
  if v_old_driver is not null and v_old_driver <> p_driver_id and length(trim(coalesce(p_reason,''))) < 3 then
    raise exception 'REASSIGN_REASON_REQUIRED';
  end if;
  if v_old_driver is distinct from p_driver_id then
    update public.order_live_locations set status='completed', ended_at=now(), updated_at=now()
    where task_id=p_task_id and status='active';
    update public.driver_tasks set driver_id=p_driver_id, task_status='assigned', assigned_at=now(),
      accepted_at=null, started_at=null, arrived_at=null, updated_at=now() where id=p_task_id;
    update public.orders set assigned_driver_id=p_driver_id, updated_at=now() where id=v_task.order_id;
    insert into public.driver_task_events(task_id,order_id,actor_id,actor_role,action,previous_status,new_status,reason,metadata)
    values(p_task_id,v_task.order_id,auth.uid(),'admin',case when v_old_driver is null then 'driver_assigned' else 'driver_reassigned' end,
      v_task.task_status,'assigned',trim(coalesce(p_reason,'')),jsonb_build_object('previousDriverId',v_old_driver,'driverId',p_driver_id));
    if v_old_driver is not null then
      insert into public.notifications(user_id,order_id,title,body,type,link,message_params,source_event_key)
      select v_old_driver,o.id,'Task reassigned','The '||v_task.task_type||' task for order '||o.order_number||' was reassigned.',
        'driver_task_reassigned','/driver',jsonb_build_object('orderNumber',o.order_number,'taskType',v_task.task_type),
        'driver-task-reassigned-away:'||p_task_id::text||':'||extract(epoch from clock_timestamp())::bigint::text
      from public.orders o where o.id=v_task.order_id
      on conflict (user_id,order_id,source_event_key) where source_event_key is not null and order_id is not null do nothing;
    end if;
    insert into public.notifications(user_id,order_id,title,body,type,link,message_params,source_event_key)
    select p_driver_id,o.id,'New '||v_task.task_type||' task',
      'You were assigned '||v_task.task_type||' for order '||o.order_number||'.','driver_task_assigned',
      '/driver/task/'||p_task_id,jsonb_build_object('orderNumber',o.order_number,'taskType',v_task.task_type),
      'driver-task-assigned:'||p_task_id::text||':'||p_driver_id::text||':'||extract(epoch from clock_timestamp())::bigint::text
    from public.orders o where o.id=v_task.order_id
    on conflict (user_id,order_id,source_event_key) where source_event_key is not null and order_id is not null do nothing;
  end if;
  return public.driver_task_payload_v1(p_task_id, true);
end;
$$;

create or replace function public.driver_accept_task_v1(p_task_id uuid)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_task public.driver_tasks%rowtype;
begin
  if not public.is_driver() then raise exception 'DRIVER_REQUIRED'; end if;
  select * into v_task from public.driver_tasks where id=p_task_id and driver_id=auth.uid() for update;
  if not found then raise exception 'TASK_NOT_FOUND'; end if;
  if v_task.task_status = 'accepted' then return public.driver_task_payload_v1(p_task_id,false); end if;
  if v_task.task_status <> 'assigned' then raise exception 'TASK_ACTION_NOT_ALLOWED'; end if;
  update public.driver_tasks set task_status='accepted',accepted_at=now(),updated_at=now() where id=p_task_id;
  insert into public.driver_task_events(task_id,order_id,actor_id,actor_role,action,previous_status,new_status)
  values(p_task_id,v_task.order_id,auth.uid(),'driver','task_accepted','assigned','accepted');
  return public.driver_task_payload_v1(p_task_id,false);
end;
$$;

create or replace function public.driver_start_task_v1(
  p_task_id uuid, p_latitude double precision, p_longitude double precision,
  p_accuracy_meters double precision default null, p_heading_degrees double precision default null,
  p_speed_mps double precision default null
) returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_task public.driver_tasks%rowtype; v_order public.orders%rowtype; v_expected_order_status text;
begin
  if not public.is_driver() then raise exception 'DRIVER_REQUIRED'; end if;
  if p_latitude is null or p_longitude is null or p_latitude not between -90 and 90 or p_longitude not between -180 and 180 then raise exception 'INVALID_COORDINATES'; end if;
  select * into v_task from public.driver_tasks where id=p_task_id and driver_id=auth.uid() for update;
  if not found then raise exception 'TASK_NOT_FOUND'; end if;
  select * into v_order from public.orders where id=v_task.order_id for update;
  if v_task.task_status in ('en_route','arrived') then
    insert into public.order_live_locations(order_id,task_id,driver_id,phase,status,latitude,longitude,accuracy_meters,heading_degrees,speed_mps,started_at,captured_at,ended_at,updated_at)
    values(v_order.id,p_task_id,auth.uid(),v_task.task_type,'active',p_latitude,p_longitude,p_accuracy_meters,p_heading_degrees,p_speed_mps,coalesce(v_task.started_at,now()),now(),null,now())
    on conflict(order_id) do update set task_id=p_task_id,driver_id=auth.uid(),phase=v_task.task_type,status='active',latitude=p_latitude,
      longitude=p_longitude,accuracy_meters=p_accuracy_meters,heading_degrees=p_heading_degrees,speed_mps=p_speed_mps,
      captured_at=now(),ended_at=null,updated_at=now();
    perform public.enqueue_driver_arrival_notification_v1(v_order.id);
    return public.driver_task_payload_v1(p_task_id,false);
  end if;
  if v_task.task_status <> 'accepted' then raise exception 'TASK_ACCEPTANCE_REQUIRED'; end if;
  v_expected_order_status := case when v_task.task_type='pickup' then 'accepted' else 'ready' end;
  if v_task.task_type='pickup' and v_order.status not in ('accepted','pickup_in_progress') then raise exception 'ORDER_NOT_READY_FOR_TASK'; end if;
  if v_task.task_type='delivery' and v_order.status not in ('ready','out_for_delivery') then raise exception 'ORDER_NOT_READY_FOR_TASK'; end if;

  update public.orders set status=case when v_task.task_type='pickup' then 'pickup_in_progress' else 'out_for_delivery' end,
    assigned_driver_id=auth.uid(), status_comment=case when v_task.task_type='pickup' then 'Driver started pickup' else 'Driver started delivery' end,
    updated_at=now() where id=v_order.id;
  update public.driver_tasks set task_status='en_route',accepted_at=coalesce(accepted_at,now()),started_at=now(),updated_at=now() where id=p_task_id;
  insert into public.order_live_locations(order_id,task_id,driver_id,phase,status,latitude,longitude,accuracy_meters,heading_degrees,speed_mps,started_at,captured_at,ended_at,updated_at)
  values(v_order.id,p_task_id,auth.uid(),v_task.task_type,'active',p_latitude,p_longitude,p_accuracy_meters,p_heading_degrees,p_speed_mps,now(),now(),null,now())
  on conflict(order_id) do update set task_id=p_task_id,driver_id=auth.uid(),phase=v_task.task_type,status='active',latitude=p_latitude,
    longitude=p_longitude,accuracy_meters=p_accuracy_meters,heading_degrees=p_heading_degrees,speed_mps=p_speed_mps,
    started_at=now(),captured_at=now(),ended_at=null,updated_at=now();
  insert into public.driver_task_events(task_id,order_id,actor_id,actor_role,action,previous_status,new_status)
  values(p_task_id,v_order.id,auth.uid(),'driver','trip_started',v_task.task_status,'en_route');
  perform public.enqueue_driver_arrival_notification_v1(v_order.id);
  return public.driver_task_payload_v1(p_task_id,false);
end;
$$;

create or replace function public.driver_update_task_location_v1(
  p_task_id uuid, p_latitude double precision, p_longitude double precision,
  p_accuracy_meters double precision default null, p_heading_degrees double precision default null,
  p_speed_mps double precision default null
) returns void language plpgsql security definer set search_path = public, pg_temp as $$
declare v_order_id uuid;
begin
  if not public.is_driver() then raise exception 'DRIVER_REQUIRED'; end if;
  if p_latitude is null or p_longitude is null or p_latitude not between -90 and 90 or p_longitude not between -180 and 180 then raise exception 'INVALID_COORDINATES'; end if;
  select order_id into v_order_id from public.driver_tasks where id=p_task_id and driver_id=auth.uid() and task_status in ('en_route','arrived');
  if not found then raise exception 'TASK_NOT_ACTIVE'; end if;
  update public.order_live_locations set latitude=p_latitude,longitude=p_longitude,accuracy_meters=p_accuracy_meters,
    heading_degrees=p_heading_degrees,speed_mps=p_speed_mps,captured_at=now(),updated_at=now()
  where task_id=p_task_id and order_id=v_order_id and driver_id=auth.uid() and status='active';
  if not found then raise exception 'TRACKING_NOT_ACTIVE'; end if;
  perform public.enqueue_driver_arrival_notification_v1(v_order_id);
end;
$$;

create or replace function public.driver_stop_task_tracking_v1(p_task_id uuid)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_task public.driver_tasks%rowtype;
  v_stopped integer;
begin
  if not public.is_driver() then raise exception 'DRIVER_REQUIRED'; end if;
  select * into v_task from public.driver_tasks where id=p_task_id and driver_id=auth.uid();
  if not found then raise exception 'TASK_NOT_FOUND'; end if;
  if v_task.task_status not in ('en_route','arrived') then raise exception 'TASK_NOT_ACTIVE'; end if;
  update public.order_live_locations set status='completed',ended_at=now(),updated_at=now()
  where task_id=p_task_id and order_id=v_task.order_id and driver_id=auth.uid() and status='active';
  get diagnostics v_stopped = row_count;
  if v_stopped > 0 then
    insert into public.driver_task_events(task_id,order_id,actor_id,actor_role,action,previous_status,new_status)
    values(p_task_id,v_task.order_id,auth.uid(),'driver','tracking_paused',v_task.task_status,v_task.task_status);
  end if;
end;
$$;

create or replace function public.driver_arrive_task_v1(p_task_id uuid)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_task public.driver_tasks%rowtype; v_order public.orders%rowtype;
begin
  if not public.is_driver() then raise exception 'DRIVER_REQUIRED'; end if;
  select * into v_task from public.driver_tasks where id=p_task_id and driver_id=auth.uid() for update;
  if not found then raise exception 'TASK_NOT_FOUND'; end if;
  if v_task.task_status = 'arrived' then return public.driver_task_payload_v1(p_task_id,false); end if;
  if v_task.task_status <> 'en_route' then raise exception 'TASK_ACTION_NOT_ALLOWED'; end if;
  update public.driver_tasks set task_status='arrived',arrived_at=now(),updated_at=now() where id=p_task_id;
  select * into v_order from public.orders where id=v_task.order_id;
  insert into public.driver_task_events(task_id,order_id,actor_id,actor_role,action,previous_status,new_status)
  values(p_task_id,v_task.order_id,auth.uid(),'driver','driver_arrived','en_route','arrived');
  insert into public.notifications(user_id,order_id,title,body,type,link,message_params,source_event_key)
  values(v_order.user_id,v_order.id,'Your driver has arrived','Your driver has arrived for order '||v_order.order_number||'.',
    'driver_arrived','/order-tracking?orderId='||v_order.id,jsonb_build_object('orderNumber',v_order.order_number,'phase',v_task.task_type),
    'driver-arrived:'||p_task_id::text)
  on conflict (user_id,order_id,source_event_key) where source_event_key is not null and order_id is not null do nothing;
  return public.driver_task_payload_v1(p_task_id,false);
end;
$$;

create or replace function public.driver_complete_task_v1(p_task_id uuid, p_verification_code text)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_task public.driver_tasks%rowtype; v_order public.orders%rowtype; v_verify public.driver_task_verifications%rowtype;
begin
  if not public.is_driver() then raise exception 'DRIVER_REQUIRED'; end if;
  select * into v_task from public.driver_tasks where id=p_task_id and driver_id=auth.uid() for update;
  if not found then raise exception 'TASK_NOT_FOUND'; end if;
  if v_task.task_status = 'completed' then return public.driver_task_payload_v1(p_task_id,false); end if;
  if v_task.task_status <> 'arrived' then raise exception 'ARRIVAL_REQUIRED'; end if;
  select * into v_verify from public.driver_task_verifications where task_id=p_task_id for update;
  if v_verify.locked_until is not null and v_verify.locked_until > now() then
    return jsonb_build_object('error','CODE_TEMPORARILY_LOCKED','lockedUntil',v_verify.locked_until);
  end if;
  if v_verify.verification_code <> trim(coalesce(p_verification_code,'')) then
    update public.driver_task_verifications set failed_attempts=failed_attempts+1,
      locked_until=case when failed_attempts+1 >= 5 then now()+interval '10 minutes' else null end where task_id=p_task_id;
    insert into public.driver_task_events(task_id,order_id,actor_id,actor_role,action,previous_status,new_status,metadata)
    values(p_task_id,v_task.order_id,auth.uid(),'driver','verification_failed',v_task.task_status,v_task.task_status,
      jsonb_build_object('remainingAttempts',greatest(0,5-(v_verify.failed_attempts+1))));
    return jsonb_build_object('error','INVALID_VERIFICATION_CODE','remainingAttempts',greatest(0,5-(v_verify.failed_attempts+1)));
  end if;
  update public.driver_task_verifications set verified_at=now(),failed_attempts=0,locked_until=null where task_id=p_task_id;
  select * into v_order from public.orders where id=v_task.order_id for update;
  if (v_task.task_type='pickup' and v_order.status<>'pickup_in_progress') or (v_task.task_type='delivery' and v_order.status<>'out_for_delivery') then
    raise exception 'ORDER_NOT_READY_FOR_COMPLETION';
  end if;
  update public.driver_tasks set task_status='completed',completed_at=now(),updated_at=now() where id=p_task_id;
  update public.orders set status=case when v_task.task_type='pickup' then 'picked_up' else 'delivered' end,
    status_comment=case when v_task.task_type='pickup' then 'Pickup confirmed by driver' else 'Delivery confirmed by driver' end,
    updated_at=now() where id=v_order.id;
  update public.order_live_locations set status='completed',ended_at=now(),updated_at=now()
    where task_id=p_task_id and status='active';
  insert into public.driver_task_events(task_id,order_id,actor_id,actor_role,action,previous_status,new_status,metadata)
  values(p_task_id,v_order.id,auth.uid(),'driver','task_completed','arrived','completed',jsonb_build_object('verification','customer_code'));
  return public.driver_task_payload_v1(p_task_id,false);
end;
$$;

create or replace function public.driver_report_task_issue_v1(p_task_id uuid, p_reason text, p_notes text default '')
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_task public.driver_tasks%rowtype; v_issue_id uuid;
begin
  if not public.is_driver() then raise exception 'DRIVER_REQUIRED'; end if;
  if length(trim(coalesce(p_reason,''))) < 3 then raise exception 'ISSUE_REASON_REQUIRED'; end if;
  select * into v_task from public.driver_tasks where id=p_task_id and driver_id=auth.uid() for update;
  if not found then raise exception 'TASK_NOT_FOUND'; end if;
  if v_task.task_status not in ('assigned','accepted','en_route','arrived') then raise exception 'TASK_ACTION_NOT_ALLOWED'; end if;
  update public.driver_tasks set task_status='failed',failed_at=now(),updated_at=now() where id=p_task_id;
  update public.order_live_locations set status='completed',ended_at=now(),updated_at=now() where task_id=p_task_id and status='active';
  insert into public.driver_task_issues(task_id,order_id,driver_id,reason,notes)
    values(p_task_id,v_task.order_id,auth.uid(),trim(p_reason),left(trim(coalesce(p_notes,'')),1000)) returning id into v_issue_id;
  insert into public.driver_task_events(task_id,order_id,actor_id,actor_role,action,previous_status,new_status,reason,metadata)
    values(p_task_id,v_task.order_id,auth.uid(),'driver','unable_to_complete',v_task.task_status,'failed',trim(p_reason),jsonb_build_object('issueId',v_issue_id));
  insert into public.notifications(user_id,order_id,title,body,type,link,message_params,source_event_key)
  select p.id,v_task.order_id,'Driver action required','A '||v_task.task_type||' issue needs review: '||trim(p_reason),
    'driver_task_issue','/admin/order/'||v_task.order_id,jsonb_build_object('taskId',p_task_id,'reason',trim(p_reason)),
    'driver-task-issue:'||v_issue_id::text from public.profiles p where p.role='admin'
  on conflict (user_id,order_id,source_event_key) where source_event_key is not null and order_id is not null do nothing;
  return public.driver_task_payload_v1(p_task_id,false);
end;
$$;

create or replace function public.admin_resolve_driver_issue_v1(p_issue_id uuid, p_resolution_note text)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not public.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if length(trim(coalesce(p_resolution_note,''))) < 3 then raise exception 'RESOLUTION_REQUIRED'; end if;
  update public.driver_task_issues set status='resolved',resolution_note=left(trim(p_resolution_note),1000),
    resolved_by=auth.uid(),resolved_at=now(),updated_at=now() where id=p_issue_id and status='open';
  if not found then raise exception 'ISSUE_NOT_FOUND'; end if;
end;
$$;

create or replace function public.admin_reset_driver_task_v1(p_task_id uuid, p_reason text)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_task public.driver_tasks%rowtype;
begin
  if not public.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if length(trim(coalesce(p_reason,''))) < 3 then raise exception 'OVERRIDE_REASON_REQUIRED'; end if;
  select * into v_task from public.driver_tasks where id=p_task_id for update;
  if not found then raise exception 'TASK_NOT_FOUND'; end if;
  if v_task.task_status not in ('failed','assigned','accepted') then raise exception 'TASK_RESET_NOT_ALLOWED'; end if;
  update public.driver_tasks set task_status=case when driver_id is null then 'unassigned' else 'assigned' end,
    accepted_at=null,started_at=null,arrived_at=null,failed_at=null,updated_at=now() where id=p_task_id;
  insert into public.driver_task_events(task_id,order_id,actor_id,actor_role,action,previous_status,new_status,reason)
  values(p_task_id,v_task.order_id,auth.uid(),'admin','task_reset',v_task.task_status,
    case when v_task.driver_id is null then 'unassigned' else 'assigned' end,trim(p_reason));
  return public.driver_task_payload_v1(p_task_id,true);
end;
$$;

create or replace function public.admin_complete_driver_task_v1(p_task_id uuid, p_reason text)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare v_task public.driver_tasks%rowtype; v_order public.orders%rowtype;
begin
  if not public.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if length(trim(coalesce(p_reason,''))) < 3 then raise exception 'OVERRIDE_REASON_REQUIRED'; end if;
  select * into v_task from public.driver_tasks where id=p_task_id for update;
  if not found then raise exception 'TASK_NOT_FOUND'; end if;
  if v_task.task_status='completed' then return public.driver_task_payload_v1(p_task_id,true); end if;
  if v_task.task_status not in ('assigned','accepted','en_route','arrived','failed') then raise exception 'TASK_OVERRIDE_NOT_ALLOWED'; end if;
  select * into v_order from public.orders where id=v_task.order_id for update;
  perform set_config('app.driver_admin_override','on',true);

  if v_task.task_type='pickup' then
    if v_order.status in ('accepted','pickup_in_progress') then
      update public.orders set status='picked_up',status_comment='Pickup completed by admin override: '||left(trim(p_reason),240),updated_at=now()
      where id=v_order.id;
    elsif v_order.status not in ('picked_up','received_at_store','processing','ready','ready_for_collection','out_for_delivery','delivered','collected') then
      raise exception 'ORDER_NOT_READY_FOR_OVERRIDE';
    end if;
  else
    if v_order.status in ('ready','out_for_delivery') then
      update public.orders set status='delivered',status_comment='Delivery completed by admin override: '||left(trim(p_reason),240),updated_at=now()
      where id=v_order.id;
    elsif v_order.status <> 'delivered' then
      raise exception 'ORDER_NOT_READY_FOR_OVERRIDE';
    end if;
  end if;

  update public.driver_tasks set task_status='completed',completed_at=now(),updated_at=now() where id=p_task_id;
  update public.order_live_locations set status='completed',ended_at=now(),updated_at=now()
    where task_id=p_task_id and status='active';
  update public.driver_task_issues set status='resolved',resolution_note='Admin override: '||left(trim(p_reason),960),
    resolved_by=auth.uid(),resolved_at=now(),updated_at=now() where task_id=p_task_id and status='open';
  insert into public.driver_task_events(task_id,order_id,actor_id,actor_role,action,previous_status,new_status,reason,metadata)
  values(p_task_id,v_task.order_id,auth.uid(),'admin','admin_override_completed',v_task.task_status,'completed',trim(p_reason),
    jsonb_build_object('orderStatusBefore',v_order.status,'verification','admin_override'));
  return public.driver_task_payload_v1(p_task_id,true);
end;
$$;

revoke all on function public.driver_tasks_list_v1(boolean) from public, anon;
revoke all on function public.driver_task_detail_v1(uuid) from public, anon;
revoke all on function public.customer_order_driver_tasks_v1(uuid) from public, anon;
revoke all on function public.admin_order_driver_tasks_v1(uuid) from public, anon;
revoke all on function public.admin_drivers_list_v1() from public, anon;
revoke all on function public.admin_driver_operations_v1() from public, anon;
revoke all on function public.admin_assign_driver_task_v1(uuid,uuid,text) from public, anon;
revoke all on function public.driver_accept_task_v1(uuid) from public, anon;
revoke all on function public.driver_start_task_v1(uuid,double precision,double precision,double precision,double precision,double precision) from public, anon;
revoke all on function public.driver_update_task_location_v1(uuid,double precision,double precision,double precision,double precision,double precision) from public, anon;
revoke all on function public.driver_stop_task_tracking_v1(uuid) from public, anon;
revoke all on function public.driver_arrive_task_v1(uuid) from public, anon;
revoke all on function public.driver_complete_task_v1(uuid,text) from public, anon;
revoke all on function public.driver_report_task_issue_v1(uuid,text,text) from public, anon;
revoke all on function public.admin_resolve_driver_issue_v1(uuid,text) from public, anon;
revoke all on function public.admin_reset_driver_task_v1(uuid,text) from public, anon;
revoke all on function public.admin_complete_driver_task_v1(uuid,text) from public, anon;

grant execute on function public.driver_tasks_list_v1(boolean) to authenticated;
grant execute on function public.driver_task_detail_v1(uuid) to authenticated;
grant execute on function public.customer_order_driver_tasks_v1(uuid) to authenticated;
grant execute on function public.admin_order_driver_tasks_v1(uuid) to authenticated;
grant execute on function public.admin_drivers_list_v1() to authenticated;
grant execute on function public.admin_driver_operations_v1() to authenticated;
grant execute on function public.admin_assign_driver_task_v1(uuid,uuid,text) to authenticated;
grant execute on function public.driver_accept_task_v1(uuid) to authenticated;
grant execute on function public.driver_start_task_v1(uuid,double precision,double precision,double precision,double precision,double precision) to authenticated;
grant execute on function public.driver_update_task_location_v1(uuid,double precision,double precision,double precision,double precision,double precision) to authenticated;
grant execute on function public.driver_stop_task_tracking_v1(uuid) to authenticated;
grant execute on function public.driver_arrive_task_v1(uuid) to authenticated;
grant execute on function public.driver_complete_task_v1(uuid,text) to authenticated;
grant execute on function public.driver_report_task_issue_v1(uuid,text,text) to authenticated;
grant execute on function public.admin_resolve_driver_issue_v1(uuid,text) to authenticated;
grant execute on function public.admin_reset_driver_task_v1(uuid,text) to authenticated;
grant execute on function public.admin_complete_driver_task_v1(uuid,text) to authenticated;

-- Keep legacy GPS RPCs admin-only. Drivers must go through task-scoped actions.
create or replace function public.can_manage_order_tracking_v1(p_order_id uuid)
returns boolean language sql stable security definer set search_path = public, pg_temp as $$
  select public.is_admin();
$$;

-- Routine pickup/delivery transitions belong to the assigned driver task.
-- The dedicated admin override RPC sets a transaction-local flag and records why.
create or replace function public.guard_driver_owned_order_transition_v1()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
declare v_task_type text;
begin
  if old.status is not distinct from new.status or auth.uid() is null or not public.is_admin() then return new; end if;
  v_task_type := case
    when old.status in ('accepted','pickup_in_progress') and new.status in ('pickup_in_progress','picked_up') then 'pickup'
    when old.status in ('ready','out_for_delivery') and new.status in ('out_for_delivery','delivered') then 'delivery'
    else null end;
  if v_task_type is not null
    and coalesce(current_setting('app.driver_admin_override',true),'') <> 'on'
    and exists(select 1 from public.driver_tasks t where t.order_id=new.id and t.task_type=v_task_type and t.task_status not in ('completed','cancelled'))
  then
    raise exception 'DRIVER_TASK_ACTION_REQUIRED';
  end if;
  return new;
end;
$$;
revoke all on function public.guard_driver_owned_order_transition_v1() from public, anon, authenticated;
drop trigger if exists orders_guard_driver_owned_transition_v1 on public.orders;
create trigger orders_guard_driver_owned_transition_v1 before update of status on public.orders
for each row execute function public.guard_driver_owned_order_transition_v1();

-- Correctly attribute order status history produced by driver task actions.
create or replace function public.record_order_status_v11()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
declare actor_role_value text:='system'; notification_type text; notification_title text; notification_body text;
begin
  if auth.uid() is not null then
    select case when role in ('admin','driver') then role else 'customer' end into actor_role_value
    from public.profiles where id=auth.uid();
  end if;
  if tg_op='INSERT' or old.status is distinct from new.status then
    notification_type:=case new.status
      when 'pending' then 'order_submitted' when 'accepted' then 'order_confirmed'
      when 'pickup_in_progress' then 'pickup_started' when 'picked_up' then 'laundry_picked_up'
      when 'awaiting_dropoff' then 'awaiting_dropoff' when 'received_at_store' then 'laundry_received'
      when 'processing' then 'cleaning_started' when 'ready' then 'laundry_ready'
      when 'ready_for_collection' then 'ready_for_collection' when 'out_for_delivery' then 'delivery_started'
      when 'delivered' then 'order_delivered' when 'collected' then 'order_collected'
      when 'cancelled' then 'order_cancelled' else 'order_update' end;
    notification_title:=case new.status
      when 'pending' then 'Order placed' when 'accepted' then 'Order confirmed'
      when 'pickup_in_progress' then 'Laundry pickup started' when 'picked_up' then 'Laundry picked up'
      when 'awaiting_dropoff' then 'Waiting for your laundry' when 'received_at_store' then 'Laundry received at store'
      when 'processing' then 'Cleaning started' when 'ready' then 'Laundry ready'
      when 'ready_for_collection' then 'Ready for collection' when 'out_for_delivery' then 'Out for delivery'
      when 'delivered' then 'Delivered' when 'collected' then 'Collected'
      when 'cancelled' then 'Order cancelled' else 'Order update' end;
    notification_body:=notification_title||' for order '||new.order_number||'.';
    insert into public.order_status_history(order_id,status,previous_status,new_status,actor_id,actor_role,note,comment)
      values(new.id,new.status,case when tg_op='INSERT' then null else old.status end,new.status,auth.uid(),
        coalesce(actor_role_value,'system'),coalesce(nullif(new.status_comment,''),notification_title),coalesce(new.status_comment,''));
    insert into public.notifications(user_id,order_id,title,body,type,link,title_key,message_key,message_params,source_event_key)
      values(new.user_id,new.id,notification_title,notification_body,notification_type,
        '/order-tracking?orderId='||new.id,'notification.'||notification_type||'.title',
        'notification.'||notification_type||'.message',jsonb_build_object('orderNumber',new.order_number),
        'order-status:'||new.id::text||':'||new.status||':'||extract(epoch from new.updated_at)::bigint::text)
      on conflict (user_id,order_id,source_event_key) where source_event_key is not null and order_id is not null do nothing;
  end if;
  return new;
end;
$$;

do $$
begin
  if not exists(select 1 from pg_publication where pubname='supabase_realtime') then
    execute 'create publication supabase_realtime';
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='driver_tasks') then
    alter publication supabase_realtime add table public.driver_tasks;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='driver_task_events') then
    alter publication supabase_realtime add table public.driver_task_events;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='driver_task_issues') then
    alter publication supabase_realtime add table public.driver_task_issues;
  end if;
end;
$$;

notify pgrst, 'reload schema';
commit;
